module.exports = {
    alps: require('./alps'),
    button: require('./button'),
    choc: require('./choc'),
    mychoc: require('./mychoc'),
    niceview: require('./niceview'),
    chocmini: require('./chocmini'),
    diode: require('./diode'),
    jstph: require('./jstph'),
    jumper: require('./jumper'),
    push: require('./push'),
    hole: require('./hole'),
    tentingpuck: require('./tentingpuck'),
    jumper4: require('./jumper4'),
    mx: require('./mx'),
    oled: require('./oled'),
    omron: require('./omron'),
    pad: require('./pad'),
    promicro: require('./promicro'),
    nicenano: require('./nicenano'),
    rgb: require('./rgb'),
    rotary: require('./rotary'),
    scrollwheel: require('./scrollwheel'),
    slider: require('./slider'),
    trrs: require('./trrs'),
    via: require('./via'),
}